# Generated by Django 4.2.7 on 2024-07-27 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('name_en', models.CharField(max_length=256, null=True)),
                ('name_ru', models.CharField(max_length=256, null=True)),
                ('name_uz', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IncludeExclude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('name_en', models.CharField(max_length=256, null=True)),
                ('name_ru', models.CharField(max_length=256, null=True)),
                ('name_uz', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('title_en', models.CharField(max_length=256, null=True)),
                ('title_ru', models.CharField(max_length=256, null=True)),
                ('title_uz', models.CharField(max_length=256, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=13)),
                ('duration', models.CharField(max_length=256)),
                ('duration_en', models.CharField(max_length=256, null=True)),
                ('duration_ru', models.CharField(max_length=256, null=True)),
                ('duration_uz', models.CharField(max_length=256, null=True)),
                ('person_count', models.IntegerField()),
                ('overview', models.TextField()),
                ('overview_en', models.TextField(null=True)),
                ('overview_ru', models.TextField(null=True)),
                ('overview_uz', models.TextField(null=True)),
                ('itinerary', models.TextField()),
                ('itinerary_en', models.TextField(null=True)),
                ('itinerary_ru', models.TextField(null=True)),
                ('itinerary_uz', models.TextField(null=True)),
                ('status', models.CharField(choices=[('available', 'Доступно'), ('archived', 'в архиве'), ('discount', 'скидка')], max_length=30)),
                ('discount', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tour.country')),
                ('exclude', models.ManyToManyField(related_name='tour_exclude', to='tour.includeexclude')),
                ('include', models.ManyToManyField(related_name='tour_include', to='tour.includeexclude')),
            ],
        ),
        migrations.CreateModel(
            name='TourImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='tour/')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tour_img', to='tour.tour')),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='destination/')),
                ('city', models.CharField(max_length=256)),
                ('city_en', models.CharField(max_length=256, null=True)),
                ('city_ru', models.CharField(max_length=256, null=True)),
                ('city_uz', models.CharField(max_length=256, null=True)),
                ('about', models.TextField()),
                ('about_en', models.TextField(null=True)),
                ('about_ru', models.TextField(null=True)),
                ('about_uz', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tour.country')),
            ],
        ),
    ]
