# Generated by Django 4.2.7 on 2024-07-31 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_tour_photo_delete_tourimg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='photo',
        ),
        migrations.CreateModel(
            name='TourImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='tour/')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tour_img', to='tour.tour')),
            ],
        ),
    ]
