# Generated by Django 4.2.7 on 2024-07-31 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0003_remove_tour_photo_tourimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='photo',
            field=models.ImageField(default=None, upload_to='tour/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TourImg',
        ),
    ]
